# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend\main_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1158, 834)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(132, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.main_widget = QtWidgets.QWidget(self.centralwidget)
        self.main_widget.setMinimumSize(QtCore.QSize(1100, 0))
        self.main_widget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.main_widget.setObjectName("main_widget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.main_widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 10, 621, 591))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.song_grid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.song_grid.setContentsMargins(0, 0, 0, 0)
        self.song_grid.setObjectName("song_grid")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.main_widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(740, 10, 331, 741))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.song_queue_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.song_queue_layout.setContentsMargins(0, 0, 0, 0)
        self.song_queue_layout.setSpacing(12)
        self.song_queue_layout.setObjectName("song_queue_layout")
        self.songs_played_widget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.songs_played_widget.sizePolicy().hasHeightForWidth())
        self.songs_played_widget.setSizePolicy(sizePolicy)
        self.songs_played_widget.setObjectName("songs_played_widget")
        self.song_queue_layout.addWidget(self.songs_played_widget)
        self.song_queue_widget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.song_queue_widget.setObjectName("song_queue_widget")
        self.song_queue_layout.addWidget(self.song_queue_widget)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.main_widget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(140, 660, 421, 108))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.song_btns_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.song_btns_layout.setContentsMargins(0, 0, 0, 0)
        self.song_btns_layout.setObjectName("song_btns_layout")
        self.back_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.back_btn.setStyleSheet("background-color: transparent;\n"
"border: none;\n"
"qproperty-iconSize: 50px;\n"
"\n"
"")
        self.back_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("frontend\\../../../Downloads2/play_button_left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_btn.setIcon(icon)
        self.back_btn.setFlat(False)
        self.back_btn.setObjectName("back_btn")
        self.song_btns_layout.addWidget(self.back_btn, 1, 2, 1, 1)
        self.skip_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.skip_btn.setStyleSheet("background-color: transparent;\n"
"border: none;\n"
"qproperty-iconSize: 50px;\n"
"\n"
"")
        self.skip_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("frontend\\../../../Downloads2/play_button_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.skip_btn.setIcon(icon1)
        self.skip_btn.setFlat(False)
        self.skip_btn.setObjectName("skip_btn")
        self.song_btns_layout.addWidget(self.skip_btn, 1, 0, 1, 1)
        self.pause_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pause_btn.setStyleSheet("background-color: transparent;\n"
"border: none;\n"
"qproperty-iconSize: 50px;\n"
"\n"
"")
        self.pause_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("frontend\\../../../Downloads2/pause_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause_btn.setIcon(icon2)
        self.pause_btn.setFlat(False)
        self.pause_btn.setObjectName("pause_btn")
        self.song_btns_layout.addWidget(self.pause_btn, 0, 1, 1, 1)
        self.song_progress_layout = QtWidgets.QHBoxLayout()
        self.song_progress_layout.setObjectName("song_progress_layout")
        self.progress_slider = QtWidgets.QSlider(self.gridLayoutWidget_2)
        self.progress_slider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progress_slider.setOrientation(QtCore.Qt.Horizontal)
        self.progress_slider.setObjectName("progress_slider")
        self.song_progress_layout.addWidget(self.progress_slider)
        self.song_btns_layout.addLayout(self.song_progress_layout, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.main_widget)
        spacerItem1 = QtWidgets.QSpacerItem(132, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1158, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
