# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\playlist_page\playlist_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1230, 871)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setStyleSheet("#central_widget {\n"
" background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"            stop:0 #4B0082, stop:1 #000000);\n"
"}\n"
"")
        self.central_widget.setObjectName("central_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.central_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.big_box = QtWidgets.QGroupBox(self.central_widget)
        self.big_box.setStyleSheet("QGroupBox{\n"
"   border: none;\n"
"}\n"
"")
        self.big_box.setTitle("")
        self.big_box.setFlat(True)
        self.big_box.setObjectName("big_box")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.big_box)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_box = QtWidgets.QGroupBox(self.big_box)
        self.left_box.setTitle("")
        self.left_box.setFlat(True)
        self.left_box.setObjectName("left_box")
        self.gridLayout = QtWidgets.QGridLayout(self.left_box)
        self.gridLayout.setObjectName("gridLayout")
        self.song_grid = QtWidgets.QGridLayout()
        self.song_grid.setObjectName("song_grid")
        self.label_4 = QtWidgets.QLabel(self.left_box)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.song_grid.addWidget(self.label_4, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.left_box)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.song_grid.addWidget(self.label_3, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.left_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setStyleSheet(" border: 2px solid pink;\n"
" background-color: rgba(128, 128, 128, 128);\n"
" border-radius: 50px;\n"
"color: white;\n"
"\n"
"\n"
"")
        self.label.setLineWidth(3)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.song_grid.addWidget(self.label, 0, 0, 1, 3)
        self.search_btn = QtWidgets.QPushButton(self.left_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_btn.sizePolicy().hasHeightForWidth())
        self.search_btn.setSizePolicy(sizePolicy)
        self.search_btn.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.search_btn.setFont(font)
        self.search_btn.setStyleSheet(" border: 2px solid gold;\n"
" background-color: rgba(128, 128, 128, 128);\n"
" border-radius: 30px;\n"
"color: white;\n"
"\n"
"\n"
"")
        self.search_btn.setObjectName("search_btn")
        self.song_grid.addWidget(self.search_btn, 1, 0, 1, 1)
        self.song_label = QtWidgets.QLabel(self.left_box)
        self.song_label.setStyleSheet("                    border: 2px solid pink;\n"
"                    background-color: rgba(128, 128, 128, 128);\n"
"                    border-radius: 50px;\n"
"                    color: white; ")
        self.song_label.setObjectName("song_label")
        self.song_grid.addWidget(self.song_label, 2, 0, 1, 1)
        self.gridLayout.addLayout(self.song_grid, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.horizontalLayout.addWidget(self.left_box)
        self.right_box = QtWidgets.QGroupBox(self.big_box)
        self.right_box.setTitle("")
        self.right_box.setFlat(True)
        self.right_box.setObjectName("right_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.right_box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.song_queue_widget = QtWidgets.QListWidget(self.right_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.song_queue_widget.sizePolicy().hasHeightForWidth())
        self.song_queue_widget.setSizePolicy(sizePolicy)
        self.song_queue_widget.setStyleSheet(" border: 2px solid white;\n"
" background-color: rgba(128, 128, 128, 128);\n"
" border-radius: 50px;\n"
"color: white;\n"
"\n"
"\n"
"\n"
"")
        self.song_queue_widget.setObjectName("song_queue_widget")
        self.verticalLayout.addWidget(self.song_queue_widget)
        self.horizontalLayout.addWidget(self.right_box)
        self.horizontalLayout_2.addWidget(self.big_box)
        MainWindow.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1230, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Demo Album"))
        self.search_btn.setText(_translate("MainWindow", "Find more!"))
        self.song_label.setText(_translate("MainWindow", "Song btn!"))
import resource_file_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
