# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\miniplayer\miniplayer.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1126, 431)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setStyleSheet("#central_widget {\n"
" background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"            stop:0 #4B0082, stop:1 #000000);\n"
"}\n"
"")
        self.central_widget.setObjectName("central_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.central_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_box = QtWidgets.QGroupBox(self.central_widget)
        self.main_box.setStyleSheet("QGroupBox{\n"
"   border: none;\n"
"}\n"
"")
        self.main_box.setTitle("")
        self.main_box.setFlat(True)
        self.main_box.setObjectName("main_box")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_box)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.less_main_box = QtWidgets.QGroupBox(self.main_box)
        self.less_main_box.setTitle("")
        self.less_main_box.setObjectName("less_main_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.less_main_box)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.display_box = QtWidgets.QGroupBox(self.less_main_box)
        self.display_box.setTitle("")
        self.display_box.setObjectName("display_box")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.display_box)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label234 = QtWidgets.QLabel(self.display_box)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label234.setFont(font)
        self.label234.setStyleSheet("color:white;\n"
"    \n"
"")
        self.label234.setAlignment(QtCore.Qt.AlignCenter)
        self.label234.setObjectName("label234")
        self.verticalLayout_5.addWidget(self.label234)
        self.song_name_label = QtWidgets.QLabel(self.display_box)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.song_name_label.setFont(font)
        self.song_name_label.setStyleSheet("color: white;")
        self.song_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.song_name_label.setObjectName("song_name_label")
        self.verticalLayout_5.addWidget(self.song_name_label)
        self.verticalLayout_3.addWidget(self.display_box)
        self.controller_box = QtWidgets.QGroupBox(self.less_main_box)
        self.controller_box.setMinimumSize(QtCore.QSize(0, 100))
        self.controller_box.setStyleSheet("#controller_box\n"
"{\n"
"border: none;\n"
"}")
        self.controller_box.setTitle("")
        self.controller_box.setFlat(True)
        self.controller_box.setObjectName("controller_box")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.controller_box)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pause_btn = QtWidgets.QPushButton(self.controller_box)
        self.pause_btn.setStyleSheet("qproperty-iconSize: 80px;\n"
" border: none;\n"
"\n"
"\n"
"")
        self.pause_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/white_pause_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause_btn.setIcon(icon)
        self.pause_btn.setObjectName("pause_btn")
        self.verticalLayout_4.addWidget(self.pause_btn)
        self.song_btns_box = QtWidgets.QGroupBox(self.controller_box)
        self.song_btns_box.setMinimumSize(QtCore.QSize(0, 100))
        self.song_btns_box.setStyleSheet("#song_btns_box{\n"
"border: none;}")
        self.song_btns_box.setTitle("")
        self.song_btns_box.setFlat(True)
        self.song_btns_box.setObjectName("song_btns_box")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.song_btns_box)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.back_btn = QtWidgets.QPushButton(self.song_btns_box)
        self.back_btn.setStyleSheet("qproperty-iconSize: 80px;\n"
" border: none;\n"
"\n"
"\n"
"")
        self.back_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/white_play_button_left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_btn.setIcon(icon1)
        self.back_btn.setFlat(True)
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout_3.addWidget(self.back_btn)
        self.progress_slider = QtWidgets.QScrollBar(self.song_btns_box)
        self.progress_slider.setMinimumSize(QtCore.QSize(0, 50))
        self.progress_slider.setStyleSheet("QScrollBar {\n"
"background-color:   rgba(128, 128, 128, 60);\n"
"}\n"
"\n"
"QScrollBar::handle {\n"
" background-color:  rgba(255, 105, 180, 100);\n"
" min-width: 20px;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.progress_slider.setOrientation(QtCore.Qt.Horizontal)
        self.progress_slider.setObjectName("progress_slider")
        self.horizontalLayout_3.addWidget(self.progress_slider)
        self.skip_btn = QtWidgets.QPushButton(self.song_btns_box)
        self.skip_btn.setStyleSheet("qproperty-iconSize: 80px;\n"
" border: none;\n"
"\n"
"\n"
"")
        self.skip_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/white_play_button_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.skip_btn.setIcon(icon2)
        self.skip_btn.setObjectName("skip_btn")
        self.horizontalLayout_3.addWidget(self.skip_btn)
        self.verticalLayout_4.addWidget(self.song_btns_box)
        self.verticalLayout_3.addWidget(self.controller_box)
        self.horizontalLayout_2.addWidget(self.less_main_box)
        self.horizontalLayout.addWidget(self.main_box)
        MainWindow.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1126, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label234.setText(_translate("MainWindow", "Currently playing:"))
        self.song_name_label.setText(_translate("MainWindow", "song name"))
import resource_file_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
