# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\discover_page\discover_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 907)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setStyleSheet("#central_widget {\n"
" background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"           stop:0 #4B0082, stop:0.5 #000000, stop:1 #4B0082);\n"
"}\n"
"QGroupBox {border: none;}")
        self.central_widget.setObjectName("central_widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.central_widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.albums_boxlayout = QtWidgets.QGroupBox(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.albums_boxlayout.sizePolicy().hasHeightForWidth())
        self.albums_boxlayout.setSizePolicy(sizePolicy)
        self.albums_boxlayout.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.albums_boxlayout.setStyleSheet("#groupBox {border: none;\n"
"}")
        self.albums_boxlayout.setTitle("")
        self.albums_boxlayout.setFlat(True)
        self.albums_boxlayout.setObjectName("albums_boxlayout")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.albums_boxlayout)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.album_grid = QtWidgets.QGridLayout()
        self.album_grid.setObjectName("album_grid")
        self.pushButton_7 = QtWidgets.QPushButton(self.albums_boxlayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet(" border: 2px solid white;\n"
" background-image: url(:/album_pics/img_4.png);\n"
" border-radius: 30px;\n"
"color: white;\n"
"\n"
"\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.album_grid.addWidget(self.pushButton_7, 0, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.albums_boxlayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet(" border: 2px solid white;\n"
" background-image: url(:/album_pics/img_1.png);\n"
" border-radius: 30px;\n"
"color: white;\n"
"\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.album_grid.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.albums_boxlayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet(" border: 2px solid white;\n"
" background-image: url(:/album_pics/img_30.png);\n"
" border-radius: 30px;\n"
"color: white;\n"
"text-shadow: 2px 2px 2px black;    \n"
"\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.album_grid.addWidget(self.pushButton_6, 0, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.albums_boxlayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setStyleSheet(" border: 2px solid white;\n"
" background-image: url(:/album_pics/img_5.png);\n"
" border-radius: 30px;\n"
"color: white;\n"
"\n"
"\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.album_grid.addWidget(self.pushButton_9, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.albums_boxlayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet(" border: 2px solid white;\n"
" background-image: url(:/album_pics/img_2.png);\n"
" border-radius: 30px;\n"
"color: white;\n"
"\n"
"\n"
"")
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.album_grid.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.albums_boxlayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        self.pushButton_13.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_13.setStyleSheet(" border: 2px solid white;\n"
" background-image: url(:/album_pics/img_6.png);\n"
" border-radius: 30px;\n"
"color: white;\n"
"\n"
"\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.album_grid.addWidget(self.pushButton_13, 1, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.albums_boxlayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_14.setStyleSheet(" border: 2px solid white;\n"
" background-image: url(:/album_pics/img_7.png);\n"
" border-radius: 30px;\n"
"color: white;\n"
"\n"
"\n"
"")
        self.pushButton_14.setObjectName("pushButton_14")
        self.album_grid.addWidget(self.pushButton_14, 1, 2, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.albums_boxlayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_12.setStyleSheet(" border: 2px solid white;\n"
" background-image: url(:/album_pics/img_8.png);\n"
" border-radius: 30px;\n"
"color: white;\n"
"\n"
"\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.album_grid.addWidget(self.pushButton_12, 1, 3, 1, 1)
        self.gridLayout_2.addLayout(self.album_grid, 3, 0, 1, 1)
        self.top_btns_box = QtWidgets.QGroupBox(self.albums_boxlayout)
        self.top_btns_box.setMinimumSize(QtCore.QSize(0, 100))
        self.top_btns_box.setStyleSheet("QGroupBox {border: none;}")
        self.top_btns_box.setTitle("")
        self.top_btns_box.setFlat(True)
        self.top_btns_box.setObjectName("top_btns_box")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.top_btns_box)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.top_btns_box)
        self.lineEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(40)
        self.lineEdit.setFont(font)
        self.lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
" background-color: rgba(255, 255, 255, 150); \n"
" color: black;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"\n"
"")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.groupBox_3 = QtWidgets.QGroupBox(self.top_btns_box)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.see_own_playlists_btn = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.see_own_playlists_btn.setFont(font)
        self.see_own_playlists_btn.setStyleSheet("QPushButton {\n"
" background-color: rgba(255, 255, 255, 90); \n"
" color: White;\n"
"border-radius:10px;\n"
"border: 5px solid lime;\n"
"}\n"
"\n"
"\n"
"")
        self.see_own_playlists_btn.setObjectName("see_own_playlists_btn")
        self.verticalLayout.addWidget(self.see_own_playlists_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.gridLayout_2.addWidget(self.top_btns_box, 2, 0, 1, 1)
        self.albums_box_layout = QtWidgets.QHBoxLayout()
        self.albums_box_layout.setObjectName("albums_box_layout")
        self.gridLayout_2.addLayout(self.albums_box_layout, 0, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.albums_boxlayout)
        MainWindow.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Discover Page"))
        self.pushButton_7.setText(_translate("MainWindow", "Metal \n"
"\n"
"\n"
""))
        self.pushButton.setText(_translate("MainWindow", "Winter \n"
"\n"
"\n"
"Songs"))
        self.pushButton_6.setText(_translate("MainWindow", "Summer \n"
"\n"
"\n"
"hits"))
        self.pushButton_9.setText(_translate("MainWindow", "Love \n"
"\n"
"Songs"))
        self.pushButton_4.setText(_translate("MainWindow", "Top \n"
"\n"
"\n"
"hits"))
        self.pushButton_13.setText(_translate("MainWindow", "Pop \n"
"\n"
"\n"
""))
        self.pushButton_14.setText(_translate("MainWindow", "Funky \n"
"\n"
"\n"
"Bops"))
        self.pushButton_12.setText(_translate("MainWindow", "Piano \n"
"\n"
"\n"
"Vibes"))
        self.lineEdit.setText(_translate("MainWindow", "You might like...              "))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox"))
        self.see_own_playlists_btn.setText(_translate("MainWindow", "Profile"))
import resource_file_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
